# Generated by Django 5.2.7 on 2025-10-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
